# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 2.7
python: 2.7

# Install the codecov pip dependency
install:
  - pip install codecov

# Run the unit test
script:
  - coverage run twongo.py

# Push the results back to codecov
after_success:
- codecov

#dist: xenial   # required for Python >= 3.7
#language: python
#python:
#  - "3.7"
#cache: pip3
#install:
#  - pip install -r requirements.txt
#script:
#  - python twongo.py
