# This config file is for the search tweets application provided by Twitter. https://github.com/twitterdev/search-tweets-python/tree/v2
# To run this, install the searchtweets-v2 package.
# Then run `search_tweets.py --config-file search_config.yaml --no-print-stream` in the command line.
​
# search_rules:
#     start_time: 2020-03-01  # Pandemic started approximately March time.
#     end_time: 2020-12-31    # This is when we have ALSPAC Twitter data to, but could go further later.
#     query: place_country:GB place:Wales
​
search_rules:
    start_time: 2010-01-01
    end_time: 2021-04-21
    #query: place_country:GB place:Wales
    query: from:ninadicara
​
search_params:
    tweet_fields: id,created_at,author_id,text,public_metrics,geo
    place_fields: contained_within,country,country_code,full_name,geo,id,name,place_type
    expansions: geo.place_id
    max_results: 500
​
output_params:
    save_file: True
    filename_prefix: test_tweets
    results_per_file: 100000