#!/bin/bash
## Docker container starter for twongo.py, Al Tanner, April 2019
## For full details see https://github.com/DynamicGenetics/twongo

## Move to the working directory (needed if run from GUI)
cd -- "$(dirname -- "$BASH_SOURCE")"

## Deal with control-c interrupt
trap ctrl_c INT
function ctrl_c() {
        echo;
        exit 0;
}

## Check if docker is running on system.
docker images >/dev/null 2>&1;
docker_exit_code=$?;
if [[ $docker_exit_code != 0 ]]; then 
    if ! pgrep -x "docker" > /dev/null; then
        if ! pgrep -x "dockerd" > /dev/null; then
            echo "2Docker doesn't appear to be running here.";
            echo "Please start Docker and try again. Exiting.";
            read -p "(Press enter to close.)";
            exit 1;
        fi
    fi
fi 

## Check if required files are in the working directory.
if [ ! -f $PWD/credentials ] || [ ! -f $PWD/user_list ]; then
    echo "Your credentials file and/or user_list don't appear to be here.";
    echo "Please have your credentials file and user_list in this run folder.";
    read -p "(Press enter to close.)";
    exit 1;
fi

echo "_.~^~._.~^~._.~^  dockerhub.com/altanner/twongo  .~^~._.~^~._.~^~.";
echo "_.~^~._.~^~._.  github.com/DynamicGenetics/twongo  ^~._.~^~._.~^~.";
echo "_.~^~._.~^~._.~^  Twongo Docker Container Runner  ~^~._.~^~._.~^~.";

## If first run, get Docker image from dockerhub.
printf "\nChecking for updates... "
if ! docker images | grep -q altanner/twongo; then # this breaks on centos unless the whole script is sudo. adding sudo here doesn't help. why? no idea.
    echo "It looks like your first run on this system.";
    echo "Download may take a few minutes, depending on connection speed.";
    read -p "Should I continue? (y/n): " download_reply;
    while ! [[ "$download_reply" =~ ^[yn]$ ]]; do
        read -p "(y/n): " download_reply;
    done;  
    if [[ $download_reply = "n" ]]; then
        read -p "OK, stopping. Press enter to close.";
        exit 0;
    fi
fi
docker pull altanner/twongo:latest;

## Ask user how often to harvest.
read -p "How often would you like to harvest (in hours)? " frequency;
while ! [[ "$frequency" =~ ^[0-9]+$ ]]; do
    read -p "Please enter a valid number of hours between harvests: " frequency;
done;

## Look for a previous run - user may want to refresh their list of users.
if [ -f $PWD/STATUS ]; then
    echo "It looks like twongo has run in this folder previously.";
    read -p "Do you want to refresh your user_list? (y/n): " refresh_reply;
    while ! [[ "$refresh_reply" =~ ^[yn]$ ]]; do
        read -p "(y/n): " refresh_reply;
    done;    
fi
if [[ $refresh_reply = "y" ]]; then
    refresh=--refresh;
fi

## How long between harvest in seconds.
frequency_in_seconds=$(($frequency*3600))
## How many users does it look like?
number_of_users=$(sed '/^\s*$/d' $PWD/user_list | wc -l | sed -e 's/^[ \t]*//')
echo "OK, twongo starting, harvesting from $number_of_users users, once every $frequency hours.";
echo "If prompted, enter your password for this system to confirm Docker launch";

## If refreshing, do one refresh iteration, then loop into not refreshing like normal.
if [[ $refresh_reply = "y" ]]; then
    sudo docker run -d -v $PWD:/root/host_interface/ altanner/twongo:latest /bin/bash -c "/usr/bin/python3 /twongo/twongo.py $refresh --log; sleep $frequency_in_seconds; while true; do /usr/bin/python3 /twongo/twongo.py --log; sleep $frequency_in_seconds; done";
else  ## If not refreshing, just harvest, wait and loop.
    sudo docker run -d -v $PWD:/root/host_interface/ altanner/twongo:latest /bin/bash -c "while true; do /usr/bin/python3 /twongo/twongo.py $refresh --log; sleep $frequency_in_seconds; done";
fi

## I guess I could send this to devnull, but there might be important output here on error...
echo "That's a Docker hash identifying the container that is spinning up";
echo "_.~^~._.~^~._.~^~.  just a moment please  ~.~^~._.~^~._.~^~._.~^~.";

## Draw a doodle to give docker a moment to set things up.
waiting=11
while [ $waiting -gt 0 ]; do
    echo -ne "_";sleep 0.01;echo -ne ".";sleep 0.01;echo -ne "~";sleep 0.2;
    echo -ne "^";sleep 0.03;echo -ne "~";sleep 0.01;echo -ne ".";sleep 0.05;
    : $((waiting--))
done

## Report that things are up. Docker should error above if things went wrong.
container_name=$(sudo docker ps | sed -n 2p | awk 'END {print $NF}');
printf "\n_.~^~._.~^~._.~^~  ok, container launched  .~^~._.~^~._.~^~._.~^~.\n";
printf "\nDocker assigned your container the name \"$container_name\"";
printf "\nTo end the process, run this command: sudo docker stop $container_name";
printf "\nTo see your active containers: sudo docker ps";
printf "\nFor more information, see log files in ./twongo_logs\n\n";
echo $frequency > $PWD/.frequency

## If double-clicking icon, leave window open so users can see what happened.
read -p "Press enter to exit(!) - (your container will continue running)"

